version: "3.6"

volumes:
  ocpp-db-data:
    external: false
  node-red-data:
    external: false

networks:
  testing_network:
    # driver: bridge
    # enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.33.1.0/24
          gateway: 172.33.1.1
        # - subnet: "FE80::/64"
        #   gateway: "FE80::1"

services:
  mqtt-server:
    image: eclipse-mosquitto:2.0.10
    container_name: mqtt-server
    networks:
      testing_network:
        ipv4_address: 172.33.1.41
    ports:
      - "172.33.1.1:1883:1883"
      - "172.33.1.1:9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/esconfig/mosquitto.conf

  ocpp-db:
    image: mariadb:10.4
    container_name: ocpp-db
    networks:
      testing_network:
        ipv4_address: 172.33.1.42
    volumes:
      - ocpp-db-data:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ocpp-db
      MYSQL_USER: ocpp
      MYSQL_PASSWORD: ocpp

  steve:
    build: ./steve
    container_name: steve
    networks:
      testing_network:
        ipv4_address: 172.33.1.43
    ports:
      - "8180:8180"
      - "8443:8443"
    depends_on:
      - ocpp-db

  nodered:
    image: nodered/node-red
    container_name: nodered
    networks:
      testing_network:
        ipv4_address: 172.33.1.44
    volumes:
      - node-red-data:/data
    depends_on:
      - mqtt-server

  everest-testing:
    build: .
    container_name: everest-testing
    # tags:
    #   - "everest-testing:latest"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      testing_network:
        ipv4_address: 172.33.1.45
    ports:
      - "8849:8849"
    links:
      - "mqtt-server:localhost"
    command: /bin/bash -c "/entrypoint.sh"
    depends_on:
      - mqtt-server
      - steve
      - ocpp-db
      - nodered
      