name: docker-compose-actions-workflow
on: push
jobs:   
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build the EVerest stack
        run: docker-compose up --build everest-testing
      - name: Test
        run: docker run --rm ci_cd_testing_everest-testing:latest --entrypoint /entrypoint.sh
