name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build the EVerest stack
        run: docker-compose up -d
      - name: Test
        run: docker run --rm ci_cd_testing_everest-testing:latest --entrypoint /entrypoint.sh
