name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build the EVerest stack
        run: docker-compose up -d
